# ============ EMBEDDED REGIONS ============
# Auto-generated region definitions
# Created: 2025-10-12 15:59:43
# Image size: 1920x1057
# Window: Vidyascape 8.4.6 (HWND: 590828)

bot.gui.regions = [
    {'x': 590, 'y': 276, 'width': 28, 'height': 22, 'color': '#FF0000'},
    {'x': 944, 'y': 104, 'width': 12, 'height': 16, 'color': '#FF0000'},
    {'x': 900, 'y': 257, 'width': 11, 'height': 20, 'color': '#FF0000'},
    {'x': 946, 'y': 480, 'width': 20, 'height': 24, 'color': '#FF0000'},
    {'x': 974, 'y': 512, 'width': 23, 'height': 26, 'color': '#39221b'},
    {'x': 1041, 'y': 973, 'width': 31, 'height': 44, 'color': '#39221b'},
    {'x': 879, 'y': 983, 'width': 29, 'height': 45, 'color': '#39221b'},
    {'x': 1034, 'y': 849, 'width': 31, 'height': 21, 'color': '#39221b'},
    {'x': 1744, 'y': 765, 'width': 27, 'height': 29, 'color': '#39221b'},
    {'x': 1751, 'y': 799, 'width': 15, 'height': 14, 'color': '#39221b'},
    {'x': 1506, 'y': 934, 'width': 11, 'height': 13, 'color': '#39221b'},
    {'x': 1497, 'y': 967, 'width': 14, 'height': 18, 'color': '#39221b'},
    {'x': 1073, 'y': 590, 'width': 25, 'height': 31, 'color': '#39221b'},
    {'x': 1005, 'y': 490, 'width': 24, 'height': 31, 'color': '#39221b'},
    {'x': 1518, 'y': 977, 'width': 39, 'height': 13, 'color': '#39221b'},
]
bot.gui.update_region_selector()
bot.log('Loaded embedded regions')
# ============ END EMBEDDED REGIONS ============

while bot.is_running:
    bot.wait(0.6)

    bot.click_region(region_index=13, button='left')
    bot.click_region(region_index=13, button='left')
    bot.wait(0.6)
    bot.click_region(region_index=0, button='left')
    bot.click_region(region_index=0, button='left')
    bot.wait(12.4)
    bot.click_region(region_index=1, button='left')
    bot.click_region(region_index=1, button='left')
    bot.wait(6.2)
    bot.click_region(region_index=2, button='left')
    bot.click_region(region_index=2, button='left')
    bot.wait(5.4)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)
    bot.find_and_click_color(hex_color='#39221b', region_index=4, tolerance=3, button='left')
    bot.find_and_click_color(hex_color='#39221b', region_index=3, tolerance=3, button='left')
    bot.wait(1.2)

    bot.click_region(region_index=5, button='left')
    bot.click_region(region_index=5, button='left')
    bot.wait(6.0)
    bot.click_region(region_index=6, button='left')
    bot.click_region(region_index=6, button='left')
    bot.wait(6.0)
    bot.click_region(region_index=7, button='left')
    bot.click_region(region_index=7, button='left')
    bot.wait(6.0)
    
    bot.click_region(region_index=10, button='right')
    bot.click_region(region_index=10, button='left')
    bot.click_region(region_index=10, button='right')
    bot.click_region(region_index=14, button='left')
    bot.wait(12.0)
    bot.click_region(region_index=12, button='left')
    bot.click_region(region_index=12, button='left')
    bot.click_region(region_index=12, button='left')
    bot.wait(1.2)
    bot.click_region(region_index=12, button='left')
    bot.click_region(region_index=13, button='left')
    bot.click_region(region_index=13, button='left')
    




