while bot.is_running:
	bot.click(x=980, y=419, button='right', modifiers=[], human_like=True)
	bot.click(x=1013, y=495, button='left', modifiers=[], human_like=True)
	bot.click(x=1098, y=347, button='left', modifiers=[], human_like=True)
	bot.click(x=840, y=1034, button='left', modifiers=[], human_like=True)
	bot.wait(5.0)
	bot.click(x=1760, y=800, button='left', modifiers=[], human_like=True)
	bot.click(x=1088, y=469, button='left', modifiers=[], human_like=True)
	bot.wait(3.2)
	bot.click(x=280, y=998, button='right', modifiers=[], human_like=True)
	bot.click(x=284, y=1053, button='left', modifiers=[], human_like=True)
	bot.wait(50.0)
	bot.click(x=800, y=743, button='right', modifiers=[], human_like=True)
	bot.click(x=782, y=784, button='left', modifiers=[], human_like=True)
	bot.wait(3.2)
	bot.click(x=1045, y=268, button='right', modifiers=[], human_like=True)
	bot.click(x=1040, y=313, button='left', modifiers=[], human_like=True)
	bot.wait(4)
	bot.click(x=1096, y=622, button='left', modifiers=[], human_like=True)
	bot.click(x=1096, y=622, button='left', modifiers=[], human_like=True)