# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bot_pb2 as bot__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BotServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteScript = channel.unary_stream(
                '/vasbot.BotService/ExecuteScript',
                request_serializer=bot__pb2.ScriptRequest.SerializeToString,
                response_deserializer=bot__pb2.ScriptLog.FromString,
                _registered_method=True)
        self.StopScript = channel.unary_unary(
                '/vasbot.BotService/StopScript',
                request_serializer=bot__pb2.StopRequest.SerializeToString,
                response_deserializer=bot__pb2.StopResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/vasbot.BotService/GetStatus',
                request_serializer=bot__pb2.StatusRequest.SerializeToString,
                response_deserializer=bot__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/vasbot.BotService/Ping',
                request_serializer=bot__pb2.PingRequest.SerializeToString,
                response_deserializer=bot__pb2.PingResponse.FromString,
                _registered_method=True)
        self.CheckHealth = channel.unary_unary(
                '/vasbot.BotService/CheckHealth',
                request_serializer=bot__pb2.HealthRequest.SerializeToString,
                response_deserializer=bot__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.NotifyFrameUpdate = channel.unary_unary(
                '/vasbot.BotService/NotifyFrameUpdate',
                request_serializer=bot__pb2.FrameNotification.SerializeToString,
                response_deserializer=bot__pb2.FrameResponse.FromString,
                _registered_method=True)
        self.UpdateRegions = channel.unary_unary(
                '/vasbot.BotService/UpdateRegions',
                request_serializer=bot__pb2.RegionList.SerializeToString,
                response_deserializer=bot__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.SetTargetWindow = channel.unary_unary(
                '/vasbot.BotService/SetTargetWindow',
                request_serializer=bot__pb2.WindowContext.SerializeToString,
                response_deserializer=bot__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.StartRecording = channel.unary_unary(
                '/vasbot.BotService/StartRecording',
                request_serializer=bot__pb2.Empty.SerializeToString,
                response_deserializer=bot__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.StopRecording = channel.unary_unary(
                '/vasbot.BotService/StopRecording',
                request_serializer=bot__pb2.Empty.SerializeToString,
                response_deserializer=bot__pb2.RecordingResponse.FromString,
                _registered_method=True)
        self.ClickElement = channel.unary_unary(
                '/vasbot.BotService/ClickElement',
                request_serializer=bot__pb2.ElementRequest.SerializeToString,
                response_deserializer=bot__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.TypeIntoElement = channel.unary_unary(
                '/vasbot.BotService/TypeIntoElement',
                request_serializer=bot__pb2.TypeRequest.SerializeToString,
                response_deserializer=bot__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.WaitWindow = channel.unary_unary(
                '/vasbot.BotService/WaitWindow',
                request_serializer=bot__pb2.WindowRequest.SerializeToString,
                response_deserializer=bot__pb2.UpdateResponse.FromString,
                _registered_method=True)


class BotServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ExecuteScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyFrameUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRegions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTargetWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClickElement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TypeIntoElement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WaitWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteScript': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteScript,
                    request_deserializer=bot__pb2.ScriptRequest.FromString,
                    response_serializer=bot__pb2.ScriptLog.SerializeToString,
            ),
            'StopScript': grpc.unary_unary_rpc_method_handler(
                    servicer.StopScript,
                    request_deserializer=bot__pb2.StopRequest.FromString,
                    response_serializer=bot__pb2.StopResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=bot__pb2.StatusRequest.FromString,
                    response_serializer=bot__pb2.StatusResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=bot__pb2.PingRequest.FromString,
                    response_serializer=bot__pb2.PingResponse.SerializeToString,
            ),
            'CheckHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckHealth,
                    request_deserializer=bot__pb2.HealthRequest.FromString,
                    response_serializer=bot__pb2.HealthResponse.SerializeToString,
            ),
            'NotifyFrameUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyFrameUpdate,
                    request_deserializer=bot__pb2.FrameNotification.FromString,
                    response_serializer=bot__pb2.FrameResponse.SerializeToString,
            ),
            'UpdateRegions': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRegions,
                    request_deserializer=bot__pb2.RegionList.FromString,
                    response_serializer=bot__pb2.UpdateResponse.SerializeToString,
            ),
            'SetTargetWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTargetWindow,
                    request_deserializer=bot__pb2.WindowContext.FromString,
                    response_serializer=bot__pb2.UpdateResponse.SerializeToString,
            ),
            'StartRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRecording,
                    request_deserializer=bot__pb2.Empty.FromString,
                    response_serializer=bot__pb2.UpdateResponse.SerializeToString,
            ),
            'StopRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRecording,
                    request_deserializer=bot__pb2.Empty.FromString,
                    response_serializer=bot__pb2.RecordingResponse.SerializeToString,
            ),
            'ClickElement': grpc.unary_unary_rpc_method_handler(
                    servicer.ClickElement,
                    request_deserializer=bot__pb2.ElementRequest.FromString,
                    response_serializer=bot__pb2.UpdateResponse.SerializeToString,
            ),
            'TypeIntoElement': grpc.unary_unary_rpc_method_handler(
                    servicer.TypeIntoElement,
                    request_deserializer=bot__pb2.TypeRequest.FromString,
                    response_serializer=bot__pb2.UpdateResponse.SerializeToString,
            ),
            'WaitWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.WaitWindow,
                    request_deserializer=bot__pb2.WindowRequest.FromString,
                    response_serializer=bot__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vasbot.BotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vasbot.BotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BotService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vasbot.BotService/ExecuteScript',
            bot__pb2.ScriptRequest.SerializeToString,
            bot__pb2.ScriptLog.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vasbot.BotService/StopScript',
            bot__pb2.StopRequest.SerializeToString,
            bot__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vasbot.BotService/GetStatus',
            bot__pb2.StatusRequest.SerializeToString,
            bot__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vasbot.BotService/Ping',
            bot__pb2.PingRequest.SerializeToString,
            bot__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vasbot.BotService/CheckHealth',
            bot__pb2.HealthRequest.SerializeToString,
            bot__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NotifyFrameUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vasbot.BotService/NotifyFrameUpdate',
            bot__pb2.FrameNotification.SerializeToString,
            bot__pb2.FrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRegions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vasbot.BotService/UpdateRegions',
            bot__pb2.RegionList.SerializeToString,
            bot__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTargetWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vasbot.BotService/SetTargetWindow',
            bot__pb2.WindowContext.SerializeToString,
            bot__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vasbot.BotService/StartRecording',
            bot__pb2.Empty.SerializeToString,
            bot__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vasbot.BotService/StopRecording',
            bot__pb2.Empty.SerializeToString,
            bot__pb2.RecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClickElement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vasbot.BotService/ClickElement',
            bot__pb2.ElementRequest.SerializeToString,
            bot__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TypeIntoElement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vasbot.BotService/TypeIntoElement',
            bot__pb2.TypeRequest.SerializeToString,
            bot__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WaitWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vasbot.BotService/WaitWindow',
            bot__pb2.WindowRequest.SerializeToString,
            bot__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
